import DockerfileBase from "./base.ts";
import Step from "./step.ts";

class Dockerfile extends DockerfileBase {
  steps: Step[];

  constructor() {
    super();
    this.steps = [];
  }

  withStep(step: Step) {
    this.steps.push(step);
    this.commands.push(`\n# ${step.name}`);
    this.commands.push(`# ${step.description}`);
    this.commands = this.commands.concat(step.commands);
    return this;
  }

  toString(): string {
    return (
      "# Do not edit this file directly. It is generated by FluentDocker.\n\n" +
      super.toString()
    );
  }
}

export default Dockerfile;
